version: "3.1"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my_network

  fivvy-app-container:
    image: magdaly/fivvy-app
    container_name: fivvy-app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - my_network

networks:
  my_network:
    driver: bridge